# -*- coding: utf-8 -*-
"""CSES Problem Set Coin Piles.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10smn6uwgTZ4dTjcUl24YcliEyzzcZ5fw

a,b

x = 2 from a and 1 from b
y = 2 from b and 1 from a

a = 2x + 1y  ------------ (i)
b = 2y + 1x  ------------ (ii) 

(i) *2 =>
2a = 4x + 2y ---------------(iii)
(ii)*2 =>
2b = 4y + 2x --------------(iv)

(iii)-(ii) =>
 2a - b = 3x Ans.

(iv)-(i) =>
2b - a = 3y Ans.
"""

for i in range(int(input())):
  a,b = map(int, input().split())
  if 2*a-b >=0 and (2*a-b)%3==0 and 2*b-a >= 0 and (2*b-a)%3==0:
    print("YES")

  else:
    print("NO")